export var NatoAlphabet = {
	"a": "Alpha",
	"b": "Bravo",
	"c": "Charlie",
	"d": "Delta",
	"e": "Echo",
	"f": "Foxtrot",
	"g": "Golf",
	"h": "Hotel",
	"i": "India",
	"j": "Juliett",
	"k": "Kilo",
	"l": "Lima",
	"m": "Mike",
	"n": "November",
	"o": "Oscar",
	"p": "Papa",
	"q": "Quebec",
	"r": "Romeo",
	"s": "Siera",
	"t": "Tango",
	"u": "Uniform",
	"v": "Victor",
	"w": "Wiskey",
	"x": "X-ray",
	"y": "Yankee",
	"z": "Zulu"
  };